services:
  backend:
    build:
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./backend:/app/backend:z
      - /app/backend/.venv
    ports:
      - "8000:8000"
    environment:
      ENVIRONMENT: development
    command:
      - uvicorn
      - src.api:api.app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - --reload

  db:
    ports:
      - "5433:5432"

networks:
  internal:
    internal: false