services:
  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data


  app:
    build:
      context: .
      dockerfile: ./Dockerfile.pg
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata: