"""empty message

Revision ID: 56b4fbebcf6f
Revises: 7fd62a55b49a
Create Date: 2026-02-26 20:42:32.702468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b4fbebcf6f'
down_revision: Union[str, Sequence[str], None] = '7fd62a55b49a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('tracks_user_id_key'), 'tracks', type_='unique')
    op.create_unique_constraint(None, 'tracks', ['owner_id'])
    op.drop_constraint(op.f('tracks_user_id_fkey'), 'tracks', type_='foreignkey')
    op.create_foreign_key(None, 'tracks', 'users', ['owner_id'], ['id'])
    op.drop_column('tracks', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.create_foreign_key(op.f('tracks_user_id_fkey'), 'tracks', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tracks', type_='unique')
    op.create_unique_constraint(op.f('tracks_user_id_key'), 'tracks', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('tracks', 'owner_id')
    # ### end Alembic commands ###
