"""empty message

Revision ID: a654527cf757
Revises: 56b4fbebcf6f
Create Date: 2026-02-28 13:06:31.138539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a654527cf757'
down_revision: Union[str, Sequence[str], None] = '56b4fbebcf6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'photo_url',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(op.f('tracks_owner_id_key'), 'tracks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('tracks_owner_id_key'), 'tracks', ['owner_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('tracks', 'photo_url',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
