"""empty message

Revision ID: da34721811f6
Revises: ea68ddaae04e
Create Date: 2026-01-31 21:41:23.781654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da34721811f6'
down_revision: Union[str, Sequence[str], None] = 'ea68ddaae04e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('user_username', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_profiles')
    # ### end Alembic commands ###
