"""empty message

Revision ID: ed04b9ddf6a3
Revises: 9941ae0804fb
Create Date: 2026-02-13 16:50:36.344447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed04b9ddf6a3'
down_revision: Union[str, Sequence[str], None] = '9941ae0804fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_profiles', sa.Column('phone_number', sa.String(length=50), nullable=True))
    op.add_column('users_profiles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users_profiles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('users_profiles', 'phone_nuber')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_profiles', sa.Column('phone_nuber', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('users_profiles', 'updated_at')
    op.drop_column('users_profiles', 'created_at')
    op.drop_column('users_profiles', 'phone_number')
    # ### end Alembic commands ###
