"""empty message

Revision ID: f16ad4f904c6
Revises: 28040c380d33
Create Date: 2026-02-12 16:44:28.756758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16ad4f904c6'
down_revision: Union[str, Sequence[str], None] = '28040c380d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_profiles', sa.Column('country', sa.String(length=50), nullable=True))
    op.add_column('users_profiles', sa.Column('phone_nuber', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_profiles', 'phone_nuber')
    op.drop_column('users_profiles', 'country')
    # ### end Alembic commands ###
