"""empty message

Revision ID: 08571ca24c78
Revises: 796381395a43
Create Date: 2026-02-26 20:39:14.734555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08571ca24c78'
down_revision: Union[str, Sequence[str], None] = '796381395a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'tracks', ['user_id'])
    op.create_foreign_key(None, 'tracks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.drop_constraint(None, 'tracks', type_='unique')
    op.drop_column('tracks', 'user_id')
    # ### end Alembic commands ###
